// Mini base de datos de jugadores

/* var data = null;

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
	if (this.readyState === this.DONE) {
		console.log(this.responseText);
	}
});

xhr.open("GET", "https://api-football-v1.p.rapidapi.com/v2/predictions/157462");
xhr.setRequestHeader("x-rapidapi-host", "api-football-v1.p.rapidapi.com");
xhr.setRequestHeader("x-rapidapi-key", "8e24c1ddadmsh14d300e160f7af5p1e6e9cjsnf29317490fbd");

xhr.send(data);

const apiTest = get("https://api-football-v1.p.rapidapi.com/v2/players/search/{lastname}"); */


const francoArmani01 = {
    name: 'FRANCO',
    lastname: 'ARMANI',
    league: "img/leagues/LPF.png",
    leagueText: "LPF de Argentina",
    club: "img/clubs/river.png",
    clubText: "River Plate",
    bornYear: 1986,
    positions: 'ARQ',
    valored: '6M',
    playerPhoto: "img/players/armani.png"
}

const emilianoMartinez01 = {
    name: 'EMILIANO',
    lastname: 'MARTINEZ',
    league: "img/leagues/EPL.png",
    leagueText: "Premier League",
    club: "img/clubs/villa.png",
    clubText: "Aston Villa",
    bornYear: 1990,
    positions: 'ARQ',
    valored: '18M',
    playerPhoto: "img/players/martinez.png"
}

const sergioAguero01 = {
    name:                       'SERGIO',
    lastname:                   'AGÜERO',
    league:         "img/leagues/EPL.png",
    leagueText:                 "Premier League",
    club:           "img/clubs/mancity.png",
    clubText:                   "Manchester City",
    bornYear:                   1990,
    positions:                  'DEL',
    valored:                    '40M',
    playerPhoto:    "img/players/aguero.png"
}

const playersListSearch = [
    {name: sergioAguero01.name         + " " +      sergioAguero01.lastname,
        team: sergioAguero01.clubText,
        firstName: sergioAguero01.name,
        lastName: sergioAguero01.lastname,
    },
    {name: emilianoMartinez01.name     + " " +      emilianoMartinez01.lastname},
    {name: francoArmani01.name         + " " +      francoArmani01.lastname},
    {name: "ESTEBAN ANDRADA"},
    {name: "JUAN MUSSO"},
    {name: "NICOLAS OTAMENDI"},
    {name: "GERMAN PEZZELLA"},
    {name: "JUAN FOYTH"},
    {name: "RENZO SARAVIA"},
    {name: "GONZALO MONTIEL"},
    {name: "TOMAS ANDRADA"}
]

const jugadores = [
        {firstName:                 'EMILIANO',
        lastName:                   'MARTINEZ',
        name:                       'EMILIANO MARTINEZ',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/EPL.png",
        leagueText:                 "Premier League",
        leagueNation:   "img/nations/england.png",
        club:           "img/clubs/villa.png",
        clubText:                   "Aston Villa",
        bornYear:                   1990,
        positions:                  'ARQ',
        mainPosition:               'Arquero',
        otherPosition:              'Ninguna',
        valored:                    '40,00 mill. $',
        playerPhoto:    "img/players/martinez.png",
        transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",},

        {firstName:                 'EMILIANO',
        lastName:                   'MARTINEZ',
        name:                       'EMILIANO MARTINEZ',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/EPL.png",
        leagueText:                 "Premier League",
        leagueNation:   "img/nations/england.png",
        club:           "img/clubs/villa.png",
        clubText:                   "Aston Villa",
        bornYear:                   1990,
        positions:                  'ARQ',
        mainPosition:               'Arquero',
        otherPosition:              'Ninguna',
        valored:                    '40,00 mill. $',
        playerPhoto:    "img/players/martinez.png",
        transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",},

        {firstName:                 'FRANCO',
        lastName:                   'ARMANI',
        name:                       'FRANCO ARMANI',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/LPF.png",
        leagueText:                 "LPF de Argentina",
        leagueNation:   "img/nations/argentina.png",
        club:           "img/clubs/river.png",
        clubText:                   "River Plate",
        bornYear:                   1990,
        positions:                  'DEL',
        mainPosition:               'Delantero centro',
        otherPosition:              'Extremo izquierdo<br>Extremo derecho',
        valored:                    '40,00 mill. $',
        playerPhoto:    "img/players/armani.png",
        transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",},
        
        {firstName:                 'FRANCO',
        lastName:                   'ARMANI',
        name:                       'FRANCO ARMANI',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/LPF.png",
        leagueText:                 "LPF de Argentina",
        leagueNation:   "img/nations/argentina.png",
        club:           "img/clubs/river.png",
        clubText:                   "River Plate",
        bornYear:                   1990,
        positions:                  'DEL',
        mainPosition:               'Delantero centro',
        otherPosition:              'Extremo izquierdo<br>Extremo derecho',
        valored:                    '40,00 mill. $',
        playerPhoto:    "img/players/armani.png",
        transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",},

        {firstName:                 'FRANCO',
        lastName:                   'ARMANI',
        name:                       'FRANCO ARMANI',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/LPF.png",
        leagueText:                 "LPF de Argentina",
        leagueNation:   "img/nations/argentina.png",
        club:           "img/clubs/river.png",
        clubText:                   "River Plate",
        bornYear:                   1990,
        positions:                  'DEL',
        mainPosition:               'Delantero centro',
        otherPosition:              'Extremo izquierdo<br>Extremo derecho',
        valored:                    '40,00 mill. $',
        playerPhoto:    "img/players/armani.png",
        transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",},

        {firstName:                 'FRANCO',
        lastName:                   'ARMANI',
        name:                       'FRANCO ARMANI',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/LPF.png",
        leagueText:                 "LPF de Argentina",
        leagueNation:   "img/nations/argentina.png",
        club:           "img/clubs/river.png",
        clubText:                   "River Plate",
        bornYear:                   1990,
        positions:                  'DEL',
        mainPosition:               'Delantero centro',
        otherPosition:              'Extremo izquierdo<br>Extremo derecho',
        valored:                    '40,00 mill. $',
        playerPhoto:    "img/players/armani.png",
        transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",},

        {firstName:                 'WALTER',
        lastName:                   'KANNEMANN',
        name:                       'WALTER KANNEMANN',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/brasileirao.png",
        leagueText:                 "Brasileirao",
        leagueNation:   "img/nations/brazil.png",
        club:           "img/clubs/gremio.png",
        clubText:                   "Gremio",
        bornYear:                   1990,
        positions:                  'DFCI',
        mainPosition:               'Central izquierdo',
        otherPosition:              'Lateral izquierdo',
        valored:                    '8,00 mill. €',
        playerPhoto:    "img/players/kannemann2.png",
        transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",},

        {firstName:                 'LUCAS',
        lastName:                   'M. QUARTA',
        name:                       'LUCAS MARTINEZ QUARTA',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/serie a.png",
        leagueText:                 "Serie A",
        leagueNation:   "img/nations/italy.png",
        club:           "img/clubs/fiorentina.png",
        clubText:                   "Fiorentina",
        bornYear:                   1990,
        positions:                  'DFCD',
        mainPosition:               'Central derecho',
        otherPosition:              'Central izquierdo',
        valored:                    '16,00 mill. €',
        playerPhoto:    "img/players/quarta.png",
        transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",
        dynamicPlayer:  "img/dynamic players/quarta.jpg",
        loan:                       false},

        {firstName:                 'GERMAN',
        lastName:                   'PEZZELLA',
        name:                       'GERMAN PEZZELLA',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/serie a.png",
        leagueText:                 "Serie A",
        leagueNation:   "img/nations/italy.png",
        club:           "img/clubs/fiorentina.png",
        clubText:                   "Fiorentina",
        bornYear:                   1990,
        positions:                  'DFCD',
        mainPosition:               'Central derecho',
        otherPosition:              'Central izquierdo',
        valored:                    '10,00 mill. €',
        playerPhoto:    "img/players/pezzella.png",
        //transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        //sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",
        //dynamicPlayer:  "img/dynamic players/quarta.jpg",
        loan:                       false},

        {firstName:                 'NEHUEN',
        lastName:                   'PEREZ',
        name:                       'NEHUEN PEREZ',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/spain.png",
        leagueText:                 "LaLiga",
        leagueNation:   "img/nations/spain.png",
        club:           "img/clubs/granada.png",
        clubText:                   "Granada CF",
        bornYear:                   1999,
        positions:                  'DFCD',
        mainPosition:               'Central derecho',
        otherPosition:              'Central izquierdo',
        valored:                    '12,00 mill. €',
        playerPhoto:    "img/players/nehuen.png",
        //transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        //sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",
        //dynamicPlayer:  "img/dynamic players/quarta.jpg",
        loan:                       true},

        {firstName:                 'FACUNDO',
        lastName:                   'MEDINA',
        name:                       'FACUNDO MEDINA',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/ligue1.png",
        leagueText:                 "Ligue 1",
        leagueNation:   "img/nations/france.png",
        club:           "img/clubs/lens.png",
        clubText:                   "RC Lens",
        bornYear:                   1999,
        positions:                  'DFCI',
        mainPosition:               'Central izquierdo',
        otherPosition:              'Lateral izquierdo',
        valored:                    '7,00 mill. €',
        playerPhoto:    "img/players/medina new2.png",
        //transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        //sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",
        //dynamicPlayer:  "img/dynamic players/quarta.jpg",
        loan:                       false},

        {firstName:                 'NICOLAS',
        lastName:                   'OTAMENDI',
        name:                       'NICOLAS OTAMENDI',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/portugal.png",
        leagueText:                 "Primeira Liga",
        leagueNation:   "img/nations/portugal.png",
        club:           "img/clubs/benfica.png",
        clubText:                   "Benfica",
        bornYear:                   1989,
        positions:                  'DFCD',
        mainPosition:               'Central derecho',
        otherPosition:              'Central izquierdo',
        valored:                    '8,00 mill. €',
        playerPhoto:    "img/players/otamendi.png",
        //transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        //sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",
        //dynamicPlayer:  "img/dynamic players/quarta.jpg",
        loan:                       false},

        {firstName:                 'GONZALO',
        lastName:                   'MONTIEL',
        name:                       'GONZALO MONTIEL',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/lpf.png",
        leagueText:                 "LPF de Argentina",
        leagueNation:   "img/nations/argentina.png",
        club:           "img/clubs/river.png",
        clubText:                   "River Plate",
        bornYear:                   1997,
        positions:                  'LD',
        mainPosition:               'Lateral derecho',
        otherPosition:              '',
        valored:                    '8,00 mill. €',
        playerPhoto:    "img/players/montiel2.png",
        //transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        //sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",
        //dynamicPlayer:  "img/dynamic players/quarta.jpg",
        loan:                       false},

        {firstName:                 'JUAN',
        lastName:                   'FOYTH',
        name:                       'JUAN FOYTH',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/spain.png",
        leagueText:                 "LaLiga",
        leagueNation:   "img/nations/spain.png",
        club:           "img/clubs/villarreal.png",
        clubText:                   "Villarreal CF",
        bornYear:                   1997,
        positions:                  'DFCD',
        mainPosition:               'Central derecho',
        otherPosition:              'Lateral derecho',
        valored:                    '9,00 mill. €',
        playerPhoto:    "img/players/foyth2.png",
        //transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        //sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",
        //dynamicPlayer:  "img/dynamic players/quarta.jpg",
        loan:                       true},

        {firstName:                 'NICOLAS',
        lastName:                   'TAGLIAFICO',
        name:                       'NICOLAS TAGLIAFICO',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/eredivisie.png",
        leagueText:                 "Eredivisie",
        leagueNation:   "img/nations/netherlands.png",
        club:           "img/clubs/ajax.png",
        clubText:                   "Ajax",
        bornYear:                   1994,
        positions:                  'LI',
        mainPosition:               'Lateral izquierdo',
        otherPosition:              'Central izquierdo',
        valored:                    '20,00 mill. €',
        playerPhoto:    "img/players/tagliafico4.png",
        //transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        //sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",
        //dynamicPlayer:  "img/dynamic players/quarta.jpg",
        loan:                       false},

        {firstName:                 'MARCOS',
        lastName:                   'ACUÑA',
        name:                       'MARCOS ACUÑA',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/spain.png",
        leagueText:                 "LaLiga",
        leagueNation:   "img/nations/spain.png",
        club:           "img/clubs/sevilla.png",
        clubText:                   "Sevilla",
        bornYear:                   1992,
        positions:                  'LI',
        mainPosition:               'Lateral izquierdo',
        otherPosition:              'Extremo izquierdo',
        valored:                    '14,00 mill. €',
        playerPhoto:    "img/players/acuna3.png",
        //transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        //sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",
        //dynamicPlayer:  "img/dynamic players/quarta.jpg",
        loan:                       false},

        {firstName:                 'ESTEBAN',
        lastName:                   'ANDRADA',
        name:                       'ESTEBAN ANDRADA',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/lpf.png",
        leagueText:                 "LPF de Argentina",
        leagueNation:   "img/nations/argentina.png",
        club:           "img/clubs/boca.png",
        clubText:                   "Boca Juniors",
        bornYear:                   1993,
        positions:                  'ARQ',
        mainPosition:               'Arquero',
        otherPosition:              '',
        valored:                    '14,00 mill. €',
        playerPhoto:    "img/players/andrada.png",
        //transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        //sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",
        dynamicPlayer:  "img/dynamic players/andrada.jpg",
        loan:                       false},

        {firstName:                 'LEANDRO',
        lastName:                   'PAREDES',
        name:                       'LEANDRO PAREDES',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/ligue1.png",
        leagueText:                 "Ligue 1",
        leagueNation:   "img/nations/france.png",
        club:           "img/clubs/psg.png",
        clubText:                   "Paris Saint-Germain",
        bornYear:                   1995,
        positions:                  'PIV',
        mainPosition:               'Pivote',
        otherPosition:              'Interior',
        valored:                    '30,00 mill. €',
        playerPhoto:    "img/players/paredes3.png",
        //transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        //sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",
        //dynamicPlayer:  "img/dynamic players/andrada.jpg",
        loan:                       false},

        {firstName:                 'GUIDO',
        lastName:                   'RODRIGUEZ',
        name:                       'GUIDO RODRIGUEZ',
        nation:         "img/nations/argentina.png",
        league:         "img/leagues/spain.png",
        leagueText:                 "LaLiga",
        leagueNation:   "img/nations/spain.png",
        club:           "img/clubs/betis.png",
        clubText:                   "Real Betis",
        bornYear:                   1995,
        positions:                  'PIV',
        mainPosition:               'Pivote',
        otherPosition:              '',
        valored:                    '18,00 mill. €',
        playerPhoto:    "img/players/guido2.png",
        //transfermarkt:  "https://www.transfermarkt.es/franco-armani/profil/spieler/119634",
        //sofascore:      "https://www.sofascore.com/es/jugador/franco-armani/221140",
        //dynamicPlayer:  "img/dynamic players/andrada.jpg",
        loan:                       false},
]

// Base de datos y ciclos dejarlos para más tarde. Y tratar de hacerlo con Firebase. 
// Primero, vamos a trabajar con algunos jugadores y hacer que aparezcan en pantalla, y se impriman en el HTML. 

const teamsListSearch = [
    {team: sergioAguero01.clubText},
    {team: emilianoMartinez01.clubText},
    {team: francoArmani01.clubText}
]

const people = [
    {name: 'DAVID' },
    {name: 'ROCK' },
    {name: 'BROCK' },
]